services:

  front:
    build: ./front
    ports:
      - 5173:5173
    volumes:
      - ./front:/app
      - front-v-node-modules:/node_modules

  back:
    build: ./back
    depends_on:
      - mongo
    env_file: ".env"
    ports:
      - 3000:3000
    volumes:
      - ./back:/app
      - server-v-node-modules:/node_modules

  mongo:
    build: ./db
    env_file: ".env"
    volumes:
      - database-v:/data/db

volumes:
  front-v-node-modules:
    name: "front-v-node-modules"
  server-v-node-modules:
    name: "server-v-node-modules"
  database-v:
    name: "databse-v"